### PR TITLE
Trying out testing and linting in CI

### PR DESCRIPTION
**Pull request by lhao03**
I'm just experimenting.

### CODE REVIEW

**Comment by lhao03** [comment]
https://github.com/marketplace/actions/run-golangci-lint cant get this to work.

**Comment by tarikeshaq** [comment]
🎉 🚀 💃

**Comment by tarikeshaq** [comment]
This would be super useful!! Thanks for experimenting @lhao03!!

**Comment by lhao03** [comment]
@tarikeshaq thanks for fixing! Such a simple fix I didn't think of 😅

**Comment by tarikeshaq** [comment]
No worries, thank you for taking the initiative here! I'm happy to get this merged - we can remove the commented out bits in the yml file, comment out any `unused` code, and add that little error check I missed (should be safe to log.Fatal there) and it should be good to go 🚀 !

I'll also create an issue where we can discuss our testing strategy, I haven't talked about it so that we can focus on our MVP tasks, but in case anyone is specifically interested in setting up the testing infrastructure I'll open up an issue!

**Comment by lhao03** [comment]
sorry, @tarikeshaq , what do you mean by the 'add that little error check I missed' ?

**Comment by tarikeshaq** [comment]
Oops my bad! Meant the unused error from https://github.com/ubclaunchpad/news-sentiment/pull/40/files#file-backend-routes-go-L98

It's actually probably better if we just intentionally ignore it, i.e:
```
_ = json.NewEncoder(w)......
```

**Review by tarikeshaq — APPROVED** [review]
WE HAVE CI 🚀 💯 🎉 Thank you @lhao03!!!

**Pull request merged**
