### PR TITLE
Adds schema

### LINKED ISSUE #14: Decide the database schemas
# What is it
We have our mock database work [here](https://github.com/ubclaunchpad/news-sentiment/tree/main/backend/db) and we would like to decide what are the schemas we expect to work with

# Details
Since we are working with Mongo, we have the flexibility of defining a json like schema.

Some ideas based on what we already talked about:
- We'll need a definition for a user, and each user will have some of the following:
   - a name
   - an email 
   - Some type of identifier
   - a political preference
   - a list of vote identifiers
- We'll also need definitions for articles, which have the following:
   - Some type of identifier (probably the url with path)
   - Title
   - A list of vote identifiers
- We might need definitions for votes, which might have the following:
  - Some type of identifier, might be a combination of the user identifier and the article
  - The user who did the vote
  - The article the vote is for
  - The vote (we can keep this as an empty object for the time being, but a left/right could work)

# Deliverables:
Happy to have rough JSON definitions posted here as a comment on this issue. for example:

```json
{
 "user": {
   "id": "string",
   "email": "string",
   "political preference": "string"
  }
}
```

Bonus points if you add the definitions directly to the [`schema.go`](https://github.com/ubclaunchpad/news-sentiment/blob/main/backend/db/schemas.go)

### PR DESCRIPTION
**Pull request by tarikeshaq**
fixes #14 

# What is it
Adds schema definitions that we might be using, here are the schemas:

### The User
```json
{
 "id": "string",
 "name": "string",
 "email": "string",
 "preference": "string",
  "votes": []
}
```

Thoughts here:
- Initially, we don't need too much information from the user, except which articles they voted for. We might want to keep track of which articles they viewed, but we could defer that.
- We don't need to keep the email initially so I'm open to bumping that out
- Preference is a string here, but it'll be better if we can enum it or retrict it's value for our sake

### The Articles
```json
{
 "id": "string",
 "source": "string",
 "title": "string",
 "URL": "string",
  "votes": []
}
```
Thoughts here:
- We can use the URL as an ID, but I'd rather keep entries seperate. We can use UUIDs but lets keep it simple now
- Initially we have no reason to keep the text of an article for a couple of reasons:
  - It's not really useful for us unless we want to run some type of analysis (enter #24 and #23 ) but we can defer that
  - Each source will have a unique way to extract the text, and digging into HTML to extract text at this early stage sounds ugly

### The Votes
```json
{
 "id": "string",
 "userId": "string",
 "articleId": "string",
 "voteValue": "number",
}
```

Thoughts here:
- We can combine the userId and articleId for a unique id, but this works for now
- the vote value could be a bit more restrictive (i.e a boolean? a scale of 1-5?)

## What's in this PR
- [x] A description of the schema definitions
- [x] The changes in `schemas.go` reflecting the schemas
- [x] Calling into the db package from the main package
- [x] example.env which we should update as we add more env variables

## Comments?
Please feel free to comment here.

### CODE REVIEW

**Comment by lhao03** [comment]
for the user schema, would `"votes": []`be a list of vote objects (just clarifying)? and im not too sure how useful an id for each vote is, I think it can be enough to have userId and and articleId. i agree preference should eventually be an enum but we could restrict that in the frontend. also for the article if the URL ends up being the id then I don't think the id would be useful. Would a unique ID for an article be useful vs. just using the url? i think mongodb gives every entry a unique id on default but we can turn that off/supply our own.

**Comment by tarikeshaq** [comment]
Good comments @lhao03! I'll update it to get rid of the vote id, and the article ids. 

for
> would "votes": []be a list of vote objects

From the perspective of our application yes, although I think MongoDB can store references to the vote objects (as opposed to duplicating the objects), and that is what would be persisted.

**Comment by lhao03** [comment]
everything looks good to me!

**Review by lhao03 — APPROVED** [review]
looks good!

**Comment by tarikeshaq** [comment]
Thanks @lhao03!!

**Pull request merged**
