### PR TITLE
Basic server, add README, add gitignore

### LINKED ISSUE #5: Initialize Server
## What is it?
Create the basic structure of a Go server

### What you need to do
Read up a little on go, and create a program that runs a simple (albiet useless) server

### Resources:
- General go resources: https://golang.org/doc/
- Go as a server: https://golang.org/doc/articles/wiki/
- Another example for go as a server: https://gobyexample.com/http-servers

## Deliverables:
- A simple go server in the form of a PR to this repository.
- Get yourself familiar with Go and it's infrastructure, you might need to initialize a go module (`go mod init github.com/ubclaunchpad/news-sentiment`)

### PR DESCRIPTION
**Pull request by Bebo0**

### CODE REVIEW

**Comment by tarikeshaq** [comment]
Sweet!! Thanks @Bebo0! Adding the others working on the server as reviewers.

How do you feel about the structure in [the database work](https://github.com/ubclaunchpad/news-sentiment/tree/mongodb-setup/backend)

It seems like they have a nice go module setup there, we might wanna merge that one and move this `main.go` to the `backend` directory they have there. Thoughts?

**Comment by Bebo0** [comment]
@tarikeshaq hmm I don't have enough experience with Go or mongo to envision what the architecture will look like in the future, but if we're planning to deploy the backend with the database, and not connect to a database on the cloud, then yeah it seems sane to put the server code and the db code in the same place.

**Comment by achinth-b** [comment]
I have never worked with Go and its server architecture, so with my bare knowledge from my initial learning, it looks good to me!

**Review by achinth-b — APPROVED** [review]
Sick fun

**Comment by tazwar22** [comment]
I'm learning Go too right now, but this looks very clean and well organized!

**Comment by tarikeshaq** [comment]
Okay, happy to get this merged, then we reorganize things if need be once the db stuff makes it. @lhao03 @potatokim @toast682 just an FYI that I'm merging this, nothing changes on your end, we'll put stuff together once the db stuff is ready for review

**Review by tarikeshaq — APPROVED** [review]

**Pull request merged**
